TeamProjects/TellToAsk/TellToAsk/Areas/Administration/Controllers/AnswersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TellToAsk.Model;
using TellToAsk.Data;
using TellToAsk.Controllers;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using TellToAsk.Areas.Administration.Models;
using Microsoft.AspNet.Identity;

namespace TellToAsk.Areas.Administration.Controllers
{
     [Authorize(Roles = "Admin")]
    public class AnswersController : BaseController
    {

        public AnswersController(IUowData data)
            : base(data)
        {
        }
        // GET: /Administration/Aswers/
        public ActionResult Index()
        {
            var answers = this.Data.Answers.All().Select(AnswerModel.FromAnswer).ToList();
            return View(answers);
        }
              
        public ActionResult Read([DataSourceRequest] DataSourceRequest request)
        {
            var answers = this.Data.Answers.All().Select(AnswerModel.FromAnswer);

            return Json(answers.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }
        
        // GET: /Administration/Aswers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AnswerModel answer = this.Data.Answers.All().Select(AnswerModel.FromAnswer)
                .FirstOrDefault(a => a.Id == id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            return View(answer);
        }

        // POST: /Administration/Aswers/Edit/5
        // To protect from over posting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        // 
        // Example: public ActionResult Update([Bind(Include="ExampleProperty1,ExampleProperty2")] Model model)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AnswerModel answer)
        {
            if (ModelState.IsValid)
            {
                var editedAnswer = new Answer()
                {
                    AnswerId = answer.Id,
                    Comment = answer.Text,
                    DateAnswered = answer.AnsweredDate,
                    IsReported = answer.IsReported,
                };
                this.Data.Answers.Update(editedAnswer);
                this.Data.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(answer);
        }

        // GET: /Administration/Aswers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AnswerModel answer = this.Data.Answers.All().Select(AnswerModel.FromAnswer)
                .FirstOrDefault(a => a.Id == id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            return View(answer);
        }

        // POST: /Administration/Aswers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            this.Data.Answers.Delete(id);
            this.Data.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            this.Data.Dispose();
            base.Dispose(disposing);
        }
    }
}

TeamProjects/TellToAsk/TellToAsk/Areas/Administration/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TellToAsk.Model;
using TellToAsk.Data;
using TellToAsk.Controllers;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using TellToAsk.Areas.Administration.Models;

namespace TellToAsk.Areas.Administration.Controllers
{
    [Authorize(Roles = "Admin")]
    public class QuestionsController : BaseController
    {

        public QuestionsController(IUowData data)
            : base(data)
        {
        }

        // GET: /Administration/Questions/
        public ActionResult Index()
        {
            var questions = this.Data.Questions.All().Select(QuestionModel.FromQuestion);
            return View(questions.ToList());
        }

        // GET: /Administration/Questions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QuestionModelDetails question = this.Data.Questions.All()
                .Select(QuestionModelDetails.FromQuestionDetails)
                .FirstOrDefault(q => q.QuestionId == id);
            if (question == null)
            {
                return HttpNotFound();
            }

            return View(question);
        }

        public ActionResult Read([DataSourceRequest] DataSourceRequest request)
        {
            var questions = this.Data.Questions.All().Select(QuestionModel.FromQuestion);

            return Json(questions.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        // GET: /Administration/Questions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QuestionEditModel question = this.Data.Questions.All()
                .Select(QuestionEditModel.FromEditQuestion).FirstOrDefault(q => q.Id == id);
            if (question == null)
            {
                return HttpNotFound();
            }
            ViewBag.Category = new SelectList(this.Data.Categories.All(), "CategoryId", "Name", question.Category);
            return View(question);
        }

        // POST: /Administration/Questions/Edit/5
        // To protect from over posting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        // 
        // Example: public ActionResult Update([Bind(Include="ExampleProperty1,ExampleProperty2")] Model model)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(QuestionEditModel question)
        {
            if (ModelState.IsValid)
            {
                var category = this.Data.Categories.GetById(question.Category);
                var editedQuestion = this.Data.Questions.GetById(question.Id);
                if (editedQuestion == null)
                {
                    return HttpNotFound();
                }
                editedQuestion.Title = question.Title;
                editedQuestion.Text = question.Content;
                editedQuestion.IsApproved = question.IsApproved;
                editedQuestion.Category = category;
                this.Data.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Category = this.Data.Categories.All().ToList()
                .Select(x => new SelectListItem { Text = x.Name, Value = x.CategoryId.ToString(), Selected = true });
            return View(question);
        }

        // GET: /Administration/Questions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QuestionModel question = this.Data.Questions.All().Select(QuestionModel.FromQuestion)
                .FirstOrDefault(q => q.QuestionId == id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // POST: /Administration/Questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var question = this.Data.Questions.GetById(id);
            this.Data.Answers.DeleteRange(a => a.Question.QuestionId == id);
            this.Data.Questions.Delete(id);
            this.Data.SaveChanges();
            return RedirectToAction("Index");
        }
        // comment
        protected override void Dispose(bool disposing)
        {
            this.Data.Dispose();
            base.Dispose(disposing);
        }
    }
}

TeamProjects/TellToAsk/TellToAsk/Areas/Administration/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TellToAsk.Controllers;
using TellToAsk.Data;
using TellToAsk.Areas.Administration.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System.Net;
using TellToAsk.Model;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;

namespace TellToAsk.Areas.Administration.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : BaseController
    {
         
        public UsersController(IUowData data)
            : base(data)
        {
        }
        //
        // GET: /Administration/Users/
        private static List<SelectListItem> genders = new List<SelectListItem>()
            { 
                new SelectListItem { Text = Gender.Male.ToString(), Value = "0" },
                new SelectListItem { Text = Gender.Female.ToString(), Value = "1" }
            };
        public ActionResult Index()
        {
            var users = this.Data.Users.All().Select(UserModel.FromUsers);
            return View(users.ToList());
        }

        public ActionResult Read([DataSourceRequest] DataSourceRequest request)
        {
            var questions = this.Data.Users.All().Select(UserModel.FromUsers);

            return Json(questions.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /Administration/Users/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserDetailsModel user = this.Data.Users.All()
                .Select(UserDetailsModel.FromUsersDetails).FirstOrDefault(u => u.UserId == id);
            if (user == null)
            {
                return HttpNotFound();
            }
         
            return View(user);
        }

        //
        // GET: /Administration/Users/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser user = this.Data.Users.GetById(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            ViewBag.Genders = genders;
            ViewBag.Roles = this.Data.Roles.All().ToList()
                .Select(x => new SelectListItem { Text = x.Name, Value = x.Id });

            return View(user);
        }        
        //
        // POST: /Administration/Users/Edit/5
        [HttpPost]
        public ActionResult Edit(ApplicationUser user)
        {
            if (ModelState.IsValid)
            {
                this.Data.Users.Update(user);
                this.Data.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Genders = genders;

            ViewBag.Roles = this.Data.Roles.All().ToList()
                .Select(x => new SelectListItem { Text = x.Name, Value = x.Id });
            return View(user);
        }

        public ActionResult AddRole(string id, string roleId)
        {
            ApplicationUser user = this.Data.Users.All().FirstOrDefault(u => u.Id == id);
            if (user == null)
            {
                return HttpNotFound();
            }
            var roleExisting = user.Roles.FirstOrDefault(x => x.RoleId == roleId);
            if (roleExisting == null)
            {
                var role = this.Data.Roles.All().FirstOrDefault(r => r.Id == roleId);
                var userRole = new UserRole()
                {
                    RoleId = roleId,
                    UserId = user.Id,
                    User = user,
                    Role = role
                };
                user.Roles.Add(userRole);
                this.Data.SaveChanges();
            }

            return PartialView("_Roles", user);
        }

        public ActionResult EditRoles(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser user = this.Data.Users.All().FirstOrDefault(u => u.Id == id);
            if (user == null)
            {
                return HttpNotFound();
            }

            ViewBag.Roles = this.Data.Roles.All().ToList()
                .Select(x => new SelectListItem { Text = x.Name, Value = x.Id });
            return PartialView("_EditRoles", user);
        }

        public ActionResult RemoveRole(string id, string roleId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser user = this.Data.Users.All().FirstOrDefault(u => u.Id == id);
            if (user == null)
            {
                return HttpNotFound();
            }
            var role = user.Roles.FirstOrDefault(x => x.RoleId == roleId);
            if (role != null)
            {
                user.Roles.Remove(role);
                this.Data.SaveChanges();
            }

            return PartialView("_Roles", user);
        }
        
        public ActionResult BanUser(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser user = this.Data.Users.All().FirstOrDefault(u => u.Id == id);
            if (user == null)
            {
                return HttpNotFound();
            }
            user.Management.DisableSignIn = true;
            this.Data.SaveChanges();
            return View();
        }

        public ActionResult UnbanUser(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser user = this.Data.Users.All().FirstOrDefault(u => u.Id == id);
            if (user == null)
            {
                return HttpNotFound();
            }
            user.Management.DisableSignIn = false;
            this.Data.SaveChanges();
            return View();
        }
    }
}

TeamProjects/TellToAsk/TellToAsk/Areas/Administration/Views/Users/Details.cshtml
@model TellToAsk.Areas.Administration.Models.UserDetailsModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>User Details</legend>
    <dl>
        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Points)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Points)
        </dd>
        <dt>
            @Html.DisplayName("Targeted Categories")
        </dt>
        @if (Model.TargetedCategories.Count() > 0)
        {
            <dd>
                <ul>
                    @foreach (var category in Model.TargetedCategories)
                    {
                        <li class=".break-word">
                            @category.Name
                        </li>
                    }
                </ul>
            </dd>
        }
        <dt>
            @Html.DisplayNameFor(model => model.Questions)
        </dt>
        @if (Model.Questions.Count() > 0)
        {
            <dd>
                <ul>
                    @foreach (var question in Model.Questions)
                    {
                        <li class=".break-word">
                            @Html.ActionLink(@question.Title, "Edit", "Questions", new { id = @question.QuestionId }, null) -
                            <span style="color:red">@question.Approved</span>
                        </li>
                    }
                </ul>
            </dd>
        }
        @if (Model.Answers.Count() > 0)
        {
            <dt>
                @Html.DisplayNameFor(model => model.Answers)
            </dt>

            <dd>
                <ul>
                    @foreach (var answer in Model.Answers)
                    {
                        <li class="break-word">
                            @Html.ActionLink(@answer.Text, "Edit", "Answers", new { id = @answer.Id }, null)
                            <span style="color:red">@answer.Reported</span>
                        </li>
                    }
                </ul>
            </dd>
        }
    </dl>

</fieldset>
<div class="form-actions">
    @Html.ActionLink("Edit", "Edit", new { id = Model.UserId }, new { @class = "btn btn-primary" }) |
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
</div>


TeamProjects/TellToAsk/TellToAsk/Areas/Administration/Views/Users/Edit.cshtml
@model TellToAsk.Model.ApplicationUser

@{
    ViewBag.Title = "Edit";
}

<h2>Edit User</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset class="form-horizontal">
        <legend>@Model.UserName</legend>
        @Html.HiddenFor(model => model.UserName)
        @Html.HiddenFor(model => model.BirthDate)
        @Html.HiddenFor(model => model.Gender)

        <div class="control-group">
            @Html.LabelFor(model => model.Points, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.Points)
                @Html.ValidationMessageFor(model => model.Points, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.Roles, new { @class = "control-label" })
            <div class="controls">
                <div id="roles-list">
                    @Html.Partial("_Roles")
                </div>
                @Ajax.ActionLink("Add Roles", "EditRoles", "Users", new { id = Model.Id }, new AjaxOptions()
                {
                    HttpMethod = "GET",
                    InsertionMode = InsertionMode.Replace,
                    UpdateTargetId = "edit-roles"
                }, new { @class = "btn btn btn-primary" })
                @if (!Model.Management.DisableSignIn)
                {
                    @Ajax.ActionLink("Ban User", "BanUser", new { id = Model.Id }, new AjaxOptions()
                    {
                        HttpMethod = "GET",
                        OnComplete = "hideBanButton"
                    }, new { @class = "btn btn btn-primary ban-user" })
                    @Ajax.ActionLink("Unban User", "UnbanUser", new { id = Model.Id }, new AjaxOptions()
                    {
                        HttpMethod = "GET",
                        OnComplete = "hideUnbanButton"
                    }, new { @class = "btn btn btn-primary unban-user begin-hiden" })
                }
                else
                {
                    @Ajax.ActionLink("Unban User", "UnbanUser", new { id = Model.Id }, new AjaxOptions()
                    {
                        HttpMethod = "GET",
                        OnComplete = "hideUnbanButton"
                    }, new { @class = "btn btn btn-primary unban-user" })
                    @Ajax.ActionLink("Ban User", "BanUser", new { id = Model.Id }, new AjaxOptions()
                    {
                        HttpMethod = "GET",
                        OnComplete = "hideBanButton"
                    }, new { @class = "btn btn btn-primary ban-user begin-hiden" })
                }
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" value="Save" class="btn btn btn-primary" />
        </div>
    </fieldset>
}

<div id="edit-roles"></div>

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>
    $(".begin-hiden").hide()
    function hideBanButton() {
        $(".ban-user").hide();
        $(".unban-user").show();
    }

    function hideUnbanButton() {
        $(".unban-user").hide();
        $(".ban-user").show();
    }
</script>

TeamProjects/TellToAsk/TellToAsk/Areas/Administration/Views/Users/Index.cshtml
@model IEnumerable<TellToAsk.Areas.Administration.Models.UserModel>

@{
    ViewBag.Title = "Users";
}

<h2>Users</h2>
@(Html.Kendo().Grid<TellToAsk.Areas.Administration.Models.UserModel>()
    .Name("users")
    .Columns(column =>
        {
            // column.Bound(p => p.UserId);
            column.Bound(p => p.Username).ClientTemplate(
                "#: Username.length > 20 ? (Username.substring(0, 20).concat('...')) : Username #").Width(180);
            column.Template(p => p.BirthDate)
                .ClientTemplate("#= BirthDate.toDateString() #").Title("Birth Date");
            column.Bound(p => p.Gender);
            column.Bound(p => p.Points);
            column.Template(p => p.Roles).ClientTemplate(
             "#= Roles.join(', ') #").Title("Roles");
            column.Template(p => @Html.Action("Edit", "Users", new { id = p.UserId }))
                .ClientTemplate("<a class='btn btn-primary' href='/Administration/Users/Edit?id=#= UserId #'>Edit</a> | " +
                "<a class='btn btn-primary' href='/Administration/Users/Details?id=#= UserId #'>Details</a>").Title("Action");
        })
     .Pageable()
     .Sortable()
     .Selectable()
     .DataSource(data => data
         .Ajax()
         .ServerOperation(true)
         .PageSize(5)
         .Events(events => events.Error("error_handler"))
         .Model(model =>
         {
             model.Id(p => p.UserId);

         })
             .Read(read => read.Action("Read", "Users")))
)

<script>
    function error_handler(e) {
        if (e.errors) {
            var message = "Errors:\n";
            $.each(e.errors, function (key, value) {
                if ('errors' in value) {
                    $.each(value.errors, function () {
                        message += this + "\n";
                    });
                }
            });
            alert(message);
        }
    }

</script>
@section Scripts{
    @Scripts.Render("~/bundles/kendo")
}

