TeamProjects/TellToAsk/TellToAsk/Areas/LoggedUser/Controllers/LoggedUserController.cs
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TellToAsk.Areas.LoggedUser.Models;
using TellToAsk.Controllers;
using TellToAsk.Data;
using Kendo.Mvc.Extensions;
using TellToAsk.Model;
using System.Web.Routing;
using System.Net;
using Newtonsoft.Json;
using System.Web.Script.Serialization;
using Microsoft.AspNet.Identity;

namespace TellToAsk.Areas.LoggedUser.Controllers
{
    //[Authorize(Roles="User")]
    [Authorize]
    public class LoggedUserController : BaseController
    {
        private const int PointsForAnswer = 10;
        private const int PointsForQuestion = 20;
        private const int PointsForUsefullAnswer = 5;
        private const int PointsForUselessAnswer = -5;

          public LoggedUserController(IUowData data)
            : base(data)
            {
            }

        public ActionResult MyQuestions()
        {
            return View();
        }

        public JsonResult GetMyQuestionsSimple([DataSourceRequest]DataSourceRequest request)
        {
            var userName = this.User.Identity.Name;

            var user = this.Data.Users.All().FirstOrDefault(u => u.UserName == userName);

            var questions =
                this.Data.Questions.All()
                .Where(u => u.Creator.Id == user.Id)
                .Select(QuestionModel.FromQuestion).OrderByDescending(m => m.NewMessagesCount);
            return Json(questions.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        // not in use
        public JsonResult GetMyQuestions([DataSourceRequest]DataSourceRequest request, int? id)
        {
            var userName = this.User.Identity.Name;

            var user = this.Data.Users.All().FirstOrDefault(u => u.UserName == userName);

            if (id != null)
            {

                var questions =
                    this.Data.Questions.All()
                    .Where(q => q.Creator.Id == user.Id && q.CategoryId == id).Select(QuestionModel.FromQuestion);

                return Json(questions.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
            }
            else
            {
                var categories = user.Categories.OrderBy(c => c.Name).AsQueryable().Select(CategoryModel.FromCategory);
                return Json(categories.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
            }


        }

        public JsonResult GetTargetedQuestions([DataSourceRequest]DataSourceRequest request)
        {
             var userName = this.User.Identity.Name;

            var user = this.Data.Users.All().FirstOrDefault(u => u.UserName == userName);

            var userCatsIds = user.Categories.AsQueryable().Select(c => c.CategoryId).ToList();

            var userAge = GetAge(user);



          var  questions = this.Data.Questions.All();

          

          questions = questions.Where(q => userCatsIds.Any(c => c == q.CategoryId));
            
          questions = questions.Where(q => q.Creator.Id != user.Id);
         
          questions = questions.Where(q => q.IsApproved);
        
          questions = questions.Where( q => !q.Answers.Any( a=> a.User.Id == user.Id));
          
          questions = questions.Where(q => !q.TargetedGender.HasValue || q.TargetedGender.Value == user.Gender);

          questions = questions.Where(q => !q.TargetedMaxAge.HasValue || q.TargetedMaxAge.Value >= userAge);
         
          questions = questions.Where(q => !q.TargetedMinAge.HasValue || q.TargetedMinAge.Value <= userAge);


          var questionsModels = questions.AsQueryable().Select(TakeQuestionModel.FromQuestion);
           

            return Json(questionsModels.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        private int GetAge(ApplicationUser user)
        {
            var bDay = (DateTime)user.BirthDate;
            var age = DateTime.Now.Year - bDay.Year;

            

            return age;
        }

        public JsonResult URIDecode(string data)
        {
            string question = this.Server.UrlDecode(data);
            return Json(question, JsonRequestBehavior.AllowGet);
        }

        public ActionResult QuestionAnswers(int? id)
        {

            var question = this.Data.Questions.All().FirstOrDefault(q => q.QuestionId == id);

            // just in case of evil hacker
            var currUserId = this.User.Identity.GetUserId();
            if (currUserId != question.Creator.Id)
            {
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
            }

            if (question != null)
            {

                var model = new QuestionModel()
                {
                    QuestionId = question.QuestionId,
                    QuestionText = question.Text,
                    QuestionTitle = question.Title,
                    CategoryId = question.CategoryId,
                    TargetedGender = question.TargetedGender != null ? (int)question.TargetedGender : -1,
                    TargetedGenderValue = question.TargetedGender != null ? question.TargetedGender.ToString() : null,
                    TargetedMaxAge = question.TargetedMaxAge,
                    TargetedMinAge = question.TargetedMinAge,
                };

                if (question.TargetedGender != null)
                {
                    model.TargetedGender = (int)question.TargetedGender; 
                }

               return View(model);
            }
            return new HttpStatusCodeResult(HttpStatusCode.NotFound);
        }

        public JsonResult GetQuestionAnswers([DataSourceRequest]DataSourceRequest request, int? id)
        {
            //// just in case of evil hacker
            //var question = this.Data.Questions.All().FirstOrDefault(q => q.QuestionId == id);

            //var currUserId = this.User.Identity.GetUserId();
            //if (currUserId != question.Creator.Id)
            //{
            //    return null;
            //}

            var answers = this.Data.Answers.All()
                .Where(q => q.Question.QuestionId == id && q.IsReported == false).OrderByDescending(x => x.DateAnswered)
                .Select(AnswerModel.FromAnswer);
            
            return Json(answers.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);

        }

        public JsonResult GetQuestionById(int id)
        {
            //// just in case of evil hacker
            //var questionFull = this.Data.Questions.All().FirstOrDefault(q => q.QuestionId == id);
            //var currUserId = this.User.Identity.GetUserId();
            //if (currUserId != questionFull.Creator.Id)
            //{
            //    return null;
            //}

            var question = this.Data.Questions.All().Select(QuestionModel.FromQuestion).FirstOrDefault(q => q.QuestionId == id);
            return Json(question, JsonRequestBehavior.AllowGet);
        }

        public JsonResult MarkAnswerAsRead(int id)
        {
            var answer = this.Data.Answers.All().FirstOrDefault(q => q.AnswerId == id);

            answer.IsRead = true;
            this.Data.SaveChanges();

            var answerModel = new List<Answer> { answer }.AsQueryable().Select(AnswerModel.FromAnswer).FirstOrDefault();

            return Json(answerModel, JsonRequestBehavior.AllowGet);
        }

        public ActionResult TakeQuestion()
        {
            // needed for check id in js
            return View(new AnswerModel());
        }

        [ValidateAntiForgeryToken]
        public ActionResult AnswerToQuestion(AnswerModel answerModel)
        {
            if (ModelState.IsValid)
            {
                var userName = this.User.Identity.Name;

                var user = this.Data.Users.All().FirstOrDefault(u => u.UserName == userName);
                var question = this.Data.Questions.All().FirstOrDefault(q => q.QuestionId == answerModel.QuestionId);

                var newAnswer = new Answer()
                {
                    IsReported = false,
                    Comment = answerModel.Comment,
                    User = user,
                    Question = question,
                    DateAnswered = DateTime.Now,
                    
                };

                this.Data.Answers.Add(newAnswer);

                this.Data.SaveChanges();
                user.Points =+ PointsForAnswer;
                this.Data.SaveChanges();
                return View("TakeQuestion", new AnswerModel());
            }

            return View("TakeQuestion", answerModel);
        }
       
        public ActionResult AskQuestion()
        {
            this.LoadDropDownModelsInViewBag();

            return View();
        }

        private void LoadDropDownModelsInViewBag()
        {
            var list = new List<SelectListItem>() { new SelectListItem() { Selected = true, Text = "---Select category---", Value = "-1" } };


            var categories = this.PopulateSuitableCategories().Select(c => new SelectListItem() { Value = c.CategoryId.ToString(), Text = c.Name }).ToList();

            list.AddRange(categories);

            ViewBag.Categories = list;


            var genders = this.PopulateGendersList();

            var listGenders = new List<SelectListItem>() { new SelectListItem() { Selected = true, Text = "---Select gender---", Value = "-1" } };

            listGenders.AddRange(genders);

            ViewBag.genders = listGenders;
        }

        [ValidateAntiForgeryToken]
        public ActionResult CreateQuestion(QuestionModel questionModel)
        {
            ValidateNewQuestiionInput(questionModel);

TeamProjects/TellToAsk/TellToAsk/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - My ASP.NET Application</title>
        @Styles.Render("~/Content/css")
        @Styles.Render("~/Content/Kendo/Themes/kendoUI")
        @RenderSection("styles", required: false)
        @Scripts.Render("~/bundles/kendo")
        @Scripts.Render("~/bundles/modernizr")

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Tell to ask", "Index", "Home", new { area = "" }, new { @class = "brand" })
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, null)</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, null)</li>
                        
                            @if (this.User.Identity.IsAuthenticated)
                            {
                                <li class="dropdown">
                                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">Questions <span class="caret"/></a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("My Questions", "MyQuestions", "LoggedUser", new { area = "LoggedUser" }, null)</li>
                                        
                                        <li>@Html.ActionLink("AskQuestion", "AskQuestion", "LoggedUser", new { area = "LoggedUser" }, null)</li>
                                        <li>@Html.ActionLink("Take Question", "TakeQuestion", "LoggedUser", new { area = "LoggedUser" }, null)</li>
                                    </ul>
                                </li>
                            }
                            @*Admin*@
                            @if (this.User.IsInRole("Admin"))
                            {
                                <li class="dropdown">
                                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">Administration <span class="caret"/></a>
                                    <ul class="dropdown-menu">
                                            <li>@Html.ActionLink("Categories", "Index", "Categories", new { area = "Administration" }, null)</li>
                                            <li>@Html.ActionLink("Questions", "Index", "Questions", new { area = "Administration" }, null)</li>
                                            <li>@Html.ActionLink("Answers", "Index", "Answers", new { area = "Administration" }, null)</li>
                                            <li>@Html.ActionLink("Users", "Index", "Users", new { area = "Administration" }, null)</li>
                                        </ul>
                                    </li>
                            }
                           
                            
                        </ul>
                        @Html.Partial("_LoginPartial")
                    </div>
                </div>
            </div>
        </div>
      
        <div class="container">
            @RenderBody()
            
            
        </div>
        
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)

        <footer class="navbar navbar-fixed-bottom text-center footer-main">
           
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
    </body>
</html>